const KEYNAMES = {
  // FEES:{		INITTHREAD: 50,PICKPOST:50	} 	, VALID_VALUE : 10
  KEYNAME_SOCKETID_2_IP: 'SOCKID2IP',
  KEYNAME_IP_2_SOCKETID: 'IP2SOCKID',
  KEYNAME_USERID_2_SOCKETID: 'USERID2SOCKID',
  KEYNAME_SOCKETID_2_USERID: 'SOCKID2USERID',

  KEYNAME_USERNAME_SOCKETID: 'USERNAME2SOCKID',
  KEYNAME_SOCKETID_USERNAME: 'SOCKID2USERNAME',

//	KEYNAME_USERUUID_SOCKETID : 'USERUUID2SOCKID' ,
//	KEYNAME_SOCKETID_USERUUID : 'SOCKID2USERUUID' ,
}; //
module.exports = {
  KEYNAMES,
};
