insert into infocarriers (name,symbol,idcode) values ('CJ대한통운', 'CJ', '04');
insert into infocarriers (name,symbol,idcode) values ('한진택배' , 'HANJIN', '05');
insert into infocarriers (name,symbol,idcode) values ('롯데택배' , 'LOTTE' , '08');
insert into infocarriers (name,symbol,idcode) values ('우체국택배' , 'POST' , '01');
insert into infocarriers (name,symbol,idcode) values ('로젠택배' , 'LOGEN', '06');
insert into infocarriers (name,symbol,idcode) values ('일양로지스' , 'ILYANG' , '11');
insert into infocarriers (name,symbol,idcode) values ('한덱스' , 'HANDEX' , '20');
insert into infocarriers (name,symbol,idcode) values ('대신택배' , 'DAESIN', '22');
insert into infocarriers (name,symbol,idcode) values ('경동택배' , 'GYUNGDONG', '23');
insert into infocarriers (name,symbol,idcode) values ('합동택배' , 'HABDONG', '32');
insert into infocarriers (name,symbol,idcode) values ('CU 편의점택배' , 'CU' , '46');
insert into infocarriers (name,symbol,idcode) values ('GS Postbox 택배', 'GS' , '24');
insert into infocarriers (name,symbol,idcode) values ('한의사랑택배' , 'HANI' ,'16');
insert into infocarriers (name,symbol,idcode) values ('천일택배' , 'CHUNIL' , '17');
insert into infocarriers (name,symbol,idcode) values ('건영택배' , 'GUNYOUNG' , '18');
insert into infocarriers (name,symbol,idcode) values ('굿투럭' 'GOOD' , '40');
insert into infocarriers (name,symbol,idcode) values ('애니트랙' 'ANI' , '43');
insert into infocarriers (name,symbol,idcode) values ('SLX택배' ,'SLX', '44');
insert into infocarriers (name,symbol,idcode) values ('우리택배(구호남택배)', 'URI' , '45');
insert into infocarriers (name,symbol,idcode) values ('우리한방택배' , 'URIHAN' , '47');
insert into infocarriers (name,symbol,idcode) values ('농협택배' , 'NONGHYUP' , '53');
insert into infocarriers (name,symbol,idcode) values ('홈픽택배' , 'HOMEPICK', '54');
insert into infocarriers (name,symbol,idcode) values ('IK물류' , 'IK' , '71');
insert into infocarriers (name,symbol,idcode) values ('성훈물류' , 'SUNGHOON' , '72');
insert into infocarriers (name,symbol,idcode) values ('용마로지스', 'YONGMA',  '74');
insert into infocarriers (name,symbol,idcode) values ('원더스퀵' ,  'WONDERS' , '75');
insert into infocarriers (name,symbol,idcode) values ('로지스밸리택배' , 'LOGIS' , '79');
insert into infocarriers (name,symbol,idcode) values ('컬리로지스' , 'CURLY' , '82');
insert into infocarriers (name,symbol,idcode) values ('풀앳홈' , 'FULL' , '85');
insert into infocarriers (name,symbol,idcode) values ('삼성전자물류', 'SAMSUNG', '86');
insert into infocarriers (name,symbol,idcode) values ('큐런택배' , 'CURUN' , '88');
insert into infocarriers (name,symbol,idcode) values ('두발히어로' ,'DOOBAL',   '89');
insert into infocarriers (name,symbol,idcode) values ('위니아딤채' , 'WINIA' , '90');
insert into infocarriers (name,symbol,idcode) values ('지니고 당일배송' , 'GENI' , '92');
insert into infocarriers (name,symbol,idcode) values ('오늘의픽업' , 'TODAYSP', '94');
insert into infocarriers (name,symbol,idcode) values ('로지스밸리' , 'LOGISVAL',  '96');
insert into infocarriers (name,symbol,idcode) values ('한샘서비스원 택배' , 'HANSAM' , '101');
insert into infocarriers (name,symbol,idcode) values ('NDEX KOREA' , 'NDEX' , '103');
insert into infocarriers (name,symbol,idcode) values ('도도플렉스(dodoflex)' , 'DODO',  '104');
insert into infocarriers (name,symbol,idcode) values ('LG전자(판토스)' , 'LG' , '107');
insert into infocarriers (name,symbol,idcode) values ('부릉' , 'VOORNG' , '110');
insert into infocarriers (name,symbol,idcode) values ('1004홈', 'ANGEL' ,  '112');
insert into infocarriers (name,symbol,idcode) values ('썬더히어로' , 'THUNDER', '113');
insert into infocarriers (name,symbol,idcode) values ('(주)팀프레시' , 'FRESH' , '116');
insert into infocarriers (name,symbol,idcode) values ('롯데칠성' , 'LOTTE7' , '118');
insert into infocarriers (name,symbol,idcode) values ('핑퐁' , 'PING' , '119');
insert into infocarriers (name,symbol,idcode) values ('발렉스 특수물류', 'VALEX' ,  '120');
insert into infocarriers (name,symbol,idcode) values ('엔티엘피스' , 'NTL' , '123');
insert into infocarriers (name,symbol,idcode) values ('GTS로지스' , 'GTS' , '125');
insert into infocarriers (name,symbol,idcode) values ('로지스팟' , 'LOGISPOT' , '127');
insert into infocarriers (name,symbol,idcode) values ('홈픽 오늘도착' , 'HOMEPICKT' , '129');
insert into infocarriers (name,symbol,idcode) values ('UFO로지스' , 'UFO' , '130');
insert into infocarriers (name,symbol,idcode) values ('딜리래빗' , 'DELI' , '131');
insert into infocarriers (name,symbol,idcode) values ('지오피' , 'GOP'  , '132');
insert into infocarriers (name,symbol,idcode) values ('에이치케이홀딩스' , 'HK' , '134');
insert into infocarriers (name,symbol,idcode) values ('HTNS' , 'HTNS' , '135');
insert into infocarriers (name,symbol,idcode) values ('케이제이티' , 'KJT' , '136');
insert into infocarriers (name,symbol,idcode) values ('더바오' , 'THEBAO' , '137');
insert into infocarriers (name,symbol,idcode) values ('라스트마일' , 'LAST' ,  '138');
insert into infocarriers (name,symbol,idcode) values ('오늘회 러쉬' , 'TODAYSH' ,  '139');
insert into infocarriers (name,symbol,idcode) values ('탱고앤고' , 'TANGO' , '142');
insert into infocarriers (name,symbol,idcode) values ('투데이' 'TODAY' , '143');
insert into infocarriers (name,symbol,idcode) values ('현대글로비스', 'GLOVIS' , '145');
insert into infocarriers (name,symbol,idcode) values ('ARGO' , 'ARGO' , '148');
insert into infocarriers (name,symbol,idcode) values ('자이언트' , 'GIANT', '151');
